export const profileData = {
  name: "Yoon-HoYong",
  title: "레벨 & 시스템 디자이너 | 게임플레이 프로토타이핑 특화 | 윤호용",
  avatar: "/yoon-profile.png",
  email: "dbsghdyd3000@gmail.com",
  phone: "+82(10)4438-4384",
  birthday: "Jan 11, 1993",
  location: "Gangnam-gu, Seoul, Republic of Korea",
  social: {
    twitter: "https://twitter.com/David_Yoon111",
  },
}

export const aboutData = {
  description: [
    "어린 시절 '바람의나라'를 통해 게임 디자이너의 꿈을 품은 이후, 현재는 서울을 기반으로 활동하며 게임의 재미와 구조를 설계하고 있습니다. 크래프톤(PUBG)에서의 약 6년 실무를 포함해 다양한 프로젝트를 거치며 레벨 디자인과 시스템 디자인의 전문성을 쌓아왔습니다.",

    "저의 핵심 역량은 경험의 흐름(Player Experience Flow) 설계와 체계적인 시스템 구축에 있습니다. 기획 의도에 최적화된 공간 구성과 장치를 배치하여 몰입감을 극대화하며, 복잡한 게임플레이 요소를 직관적인 규칙으로 풀어내 확장성 있는 시스템 아키텍처를 구축합니다.",

    "특히 *Unreal Engine(C++, Blueprint)과 Unity(C#)*를 활용한 프로토타이핑 능력도 갖추고 있으며, 머릿속의 아이디어를 신속하게 구체화하여 게임플레이를 조기에 검증함으로써, 팀이 올바른 방향으로 나아갈 수 있도록 기술적 가교 역할을 수행할 수 있습니다.",

    "앞으로도 플레이어 경험을 최우선으로 생각하며 혁신적이고 직관적인 메커니즘을 만들어가고자 합니다. 자유로운 목표가 공존하고 커뮤니티가 살아 숨 쉬는 RPG를 만드는 꿈을 향해, 게임 디자인을 숙명으로 여기며 정진하고 있습니다.",
  ],
  developHistory: [
    "저의 첫 게임 업계 발자취는 PUBG: NEW STATE에 시스템 디자이너로 입사하며 시작되었습니다. 단순한 데이터 관리부터 콘텐츠 기획 및 설계까지 담당하던 중, 레벨 디자인을 경험할 기회를 얻어 새로운 도전을 시작했습니다. 이후 게임 공간을 설계하는 레벨 디자인의 매력에 깊이 빠지게 되었습니다. 몰입감 있는 환경을 구축하고 플레이어의 동선을 유도하며, 게임플레이를 자연스럽게 풀어내는 과정에서 디자인의 진정한 재미를 깨달았습니다.",
    "그렇게 시스템 디자이너로서의 경험을 쌓은 뒤, 약 2년 동안 핵심 레벨 디자인 업무를 수행했습니다. 월드맵 지형, 주요 건축물, 스팟 구성 등을 직접 설계하며 발전시켰습니다. 내부 피드백과 플레이어 행동 데이터를 분석하여 동선을 개선하고, 의도한 건플레이(Gunplay)의 재미와 아트(Art) 요소를 유기적으로 결합하며 레벨 디자인을 주도했습니다.",
    "이후 게임 개발의 기초(Bottom-up)부터 체계적으로 배우고자 하는 의지로, NEW STATE에서 함께했던 선배들의 제안을 받아 Flyway Games의 프로젝트 MC에 합류했습니다. 이곳에서 시스템과 레벨 디자인은 물론 개발 초기 셋업 및 조직 운영 방식까지 폭넓게 경험할 수 있었습니다. 특히 복잡한 요소들을 명확한 규칙으로 정리하고, 신속한 프로토타이핑을 통해 팀이 조기에 핵심 재미를 검증하는 것의 중요성을 체득했습니다. 이러한 역량을 바탕으로 서브컬처 장르인 신규 프로젝트 KIZNA의 셋업 기회를 얻어, 시스템 아키텍처 설계를 주도하였고, 현재는 수십 종의 캐릭터 및 몬스터 데이터베이스 구축과 전투 시스템 등 프로젝트 전반을 담당하고 있습니다.",
    "현재는 시스템 디자인을 메인으로 담당하고 있으나, 직무의 경계에 갇히지 않고 프로젝트에 필요한 다양한 업무를 능동적으로 수행하고 있습니다. 과거의 레벨 디자인 경험을 포함하여 게임 개발의 전 영역에서 제가 기여할 수 있는 부분을 끊임없이 고민하며 배우는 자세로 임하고 있습니다. 게임 개발을 숙명으로 삼아 저의 다음 행보를 그려가고 있으며, 귀팀과 함께 시너지를 낼 수 있는 든든한 동료가 되기를 희망합니다.",
  ],
  services: [
    {
      icon: "Map",
      title: "레벨 디자인",
      description: "몰입감 있는 레벨 레이아웃, 환경 디자인, 공간 구성 설계",
    },
    {
      icon: "Settings",
      title: "게임 시스템 디자인",
      description: "핵심 게임플레이 시스템, 전투 메커니즘, 진행 시스템 설계 및 문서화",
    },
    {
      icon: "Zap",
      title: "게임플레이 프로토타이핑",
      description: "UE4(5), Unity, 코드(C++/C#), Blueprint를 활용한 빠른 프로토타이핑",
    },
    {
      icon: "Scale",
      title: "게임 밸런싱 & 튜닝",
      description: "게임 메커니즘 밸런싱, 시스템 조율, 콘텐츠 디자인",
    },
  ],
  majorWorks: [
    {
      company: "KRAFTON",
      companyLogo: "/images/pubg-studios-logo.png",
      project: "PUBG: NEW STATE(모바일 배틀로얄 슈팅 장르)",
      workTitle: "ParadiseFalls Spot 디자인",
      description: "세션 월드맵의 여러 지형 및 장소에 대한 레벨 디자인",
      period: "2020.04 - 2022.08",
      tags: ["레벨 디자인"],
    },
    {
      company: "KRAFTON",
      companyLogo: "/images/pubg-studios-logo.png",
      project: "PUBG: NEW STATE(모바일 배틀로얄 슈팅 장르)",
      workTitle: "TDM: TrainStation 디자인",
      description: "7분 내외의 가볍게 즐길 수 있는 팀 데스매치 시스템 디자인",
      period: "2020.04 - 2022.08",
      tags: ["시스템 디자인", "레벨 디자인", "e-스포츠"],
    },
    {
      company: "Flyway Games",
      companyLogo: "flyway-games-logo.png",
      project: "Trinity Surivors(PC 슈팅 로그라이크)",
      workTitle: "기믹 디자인 & 프로토타이핑",
      description: "게임에서 상시 작동될 함정 기믹 및 컨텐츠 프로토타이핑 작업",
      period: "2022.08 - 2024.07",
      tags: ["시스템 디자인", "프로토타이핑", "AI 디자인"],
    },
    {
      company: "KRAFTON",
      companyLogo: "/images/kizna-logo.png",
      project: "C3: KIZNA 프로젝트(모바일 서브컬처 CCG)",
      workTitle: "캐릭터 & 스킬 시스템 구축",
      description: "CCG 장르적 특성을 반영할 수 있는 RPG 캐릭터의 데이터베이스 설계",
      period: "2024.07 - 현재",
      tags: ["시스템 디자인", "데이터 아키텍처 설계"],
    },
  ],
  tools: [
    { name: "Premiere Pro", logo: "/images/tools/premiere-pro.png", category: "Video" },
    { name: "Photoshop", logo: "/images/tools/photoshop.png", category: "Design" },
    { name: "PowerPoint", logo: "/images/tools/powerpoint.png", category: "Office" },
    { name: "Word", logo: "/images/tools/word.png", category: "Office" },
    { name: "Excel", logo: "/images/tools/excel.png", category: "Office" },
    { name: "Gemini", logo: "/images/tools/gemini.png", category: "AI" },
    { name: "Suno", logo: "/images/tools/suno.png", category: "AI" },
    { name: "Claude", logo: "/images/tools/claude.png", category: "AI" },
    { name: "Cursor", logo: "/images/tools/cursor.png", category: "Dev" },
    { name: "Figma", logo: "/images/tools/figma.png", category: "Design" },
    { name: "Blender", logo: "/images/tools/blender.png", category: "3D" },
    { name: "UE4", logo: "/images/tools/unreal-engine.jpg", category: "Engine" },
    { name: "Unity", logo: "/images/tools/unity.jpg", category: "Engine" },
  ],
}

export const resumeData = {
  education: [
    {
      title: "성신고등학교 인문",
      period: "2008.03 — 2011.03",
      description: "고등학교 졸업",
    },
    {
      title: "울산대학교 사회과학부",
      period: "2015.03 — 2019.03",
      description: "사회과학부 행정학과 학사 졸업 (수석 졸업)",
    },
    {
      title: "SBS 게임 아카데미 (강남)",
      period: "2019.08.01 — 2020.01.30",
      description: "게임 개발 전문 교육 과정 (기획 / 사업 / 프로그래밍(C++))",
    },
    {
      title: "게임 엔진 및 프로그래밍 독학",
      period: "2019.10.01 — 2020.04.01",
      description:
        "인프런 (Rookiss Unity/C# - 전 테라 출신), 유튜브 (Matthew Wadstein UE4 등), Udemy (언리얼 엔진4 (Unreal Engine) 3D 횡스크롤 게임 제작) 등 학습",
    },
  ],
  experience: [
    {
      title: "PUBG(KRAFTON)/ PUBG:NewState(모바일 배틀로얄 슈팅 장르) - 시스템&레벨 디자이너",
      period: "2020.04 — 2022.08",
      description:
        "XTRM(PUBG:NewState) 프로젝트 진행 (시스템/레벨 디자이너) - NS CorePlay / Level Mode / DeepDive Team 근무 - 전투 관련 시스템(총기, 네비게이션), 레벨 디자인(스팟 및 건물 구성, TDM 제작 등), 대회 운영 컨텐츠(옵저버 시스템, 커스텀 방) 등 다양한 업무 담당",
    },
    {
      title: "FlywayGames(KRAFTON) / MC Project(PC 슈팅 로그라이크) - 시스템&레벨 디자이너",
      period: "2022.08 — 2024.07",
      description:
        "시스템/레벨 디자이너로 참여 - 몬스터&아이템 설계 및 디자인, 기믹 디자인, 컨텐츠 프로토타이핑 작업 등",
    },
    {
      title: "PUBG(KRAFTON)/ KIZNA Project(모바일 서브컬처 CCG) - 시스템 디자이너",
      period: "2024.07 — 현재",
      description:
        "시스템 디자이너로 참여 - 전반적인 게임 기반 시스템 설계, 캐릭터 & 전투 컨텐츠 시스템 설계, 기본 업무 협업 시스템 구축 등",
    },
  ],
  skills: [
    {
      name: "엔진 활용능력",
      description: "UE4 / Unity 6",
      icon: "/icon-game-engine.png",
    },
    {
      name: "레벨 디자인",
      description: "게임 레벨 설계 및 배치",
      icon: "/icon-level-design.png",
    },
    {
      name: "시스템 디자인",
      description: "게임 시스템 설계 및 구현",
      icon: "/icon-system-design.png",
    },
    {
      name: "프로토타이핑",
      description: "C++ / C# / BP(UE) 활용",
      icon: "/icon-prototyping.png",
    },
  ],
}

export const portfolioData = {
  projectCategories: ["PUBG:NewState", "KIZNA", "TrinitySurvivors"],
  projectDescriptions: {
    "PUBG:NewState":
      "PUBG: NEW STATE는 __오픈월드 세션형 배틀로얄 FPS__ 게임이고 저의 1번째 프로젝트입니다. 저는 이 프로젝트에서 약 2.5년간 레벨 및 시스템 디자이너로 활동하며 다양한 업무를 담당했습니다. 본 프로젝트에서는 주로 레벨 디자이너(70%)로서 참여 비중이 높았기에 먼저 레벨 디자이너로서 담당한 임무의 핵심 목표를 먼저 말해보자면, 큰 차원에서볼 때 '__건(Gun)플레이하기 좋은 재미있는 월드를 만드는 것__'이었습니다.\n \n이를 위해 예를들면, '어떤 건물과 프랍의 형태가 건 플레이하기에 좋을까?', '건물의 배치는 어떤 간격으로 어떤 건물과 함께 이루어지고 그 규모는 어떻게 되어야할까?', '그리하여 현재 월드 스팟들의 배치 수준이 유저의 선택에 편향되지 않고 잘 선택이 되는가?', 등의 기본적인 월드 구성에 대한 고민을 포함하여, '지금 엄폐물의 밀도와 사용하는 프랍 및 건물의 특성이 특정 공간에 밀집되었는데 교전이 이 방향으로 많이 발생하면 부하가 많이 생기지 않을까?', '건 플레이적으로 불필요한 프랍과 건물은 무엇이며, 이것의 컬링 거리가 적절한지?'와 같은 모바일 플랫폼에서 고려해야될 최적화에서 오는 고민에 이르기까지 다양한 요소들을 분석하고 해결해야하는 업무들을 해당 프로젝트에서 수행하였습니다.\n \n팀 내에서는 핵심적으로 아래와 같은 작업들을 수행하였습니다.\n \n- 월드 랜드스케이프 작업 및 스팟의 구성\n\n- 건물 혹은 프랍들에대한 기초적인 가메시(BSP)작업\n\n- 가메시 제작 및 아트와 협업 체계 가이드라인 마련\n\n- 신규 모드 TDM(Station) 제작\n\n- 개발 내부 테스트 환경을 위한 건 플레이 테스트 월드 구성\n\n- BP를 활용한 기믹 및 프로토타이핑 모드 제작\n\n- 매시(Mesh) 컬링 거리 분석\n\n- 최적화를 위한 PSO 캐싱 및 대응 작업\n \n이런 작업들의 일부 결과들에 대해서는 실제 게임의 출시까지로도 많은 부분이 이루어졌습니다. 월드-'TROI'의 지형구성과 'TROI'의 다양한 스팟과 건물('Penrose', 'Bay Area', 'Trailor Park', 'Mall', 'GraveYard', 'SunBury')등이 있으며, 팀 데스매치 작업인 Station까지 다양하게 본인의 작업을 이끌었고 그 성과를 인정 받았습니다. 그 중에서도 특히 '__MALL__'은 월드-TROI에서 가장 중앙에 위치한 스팟으로서 현재에도 월드에서 가장 많이 찾고 사랑받는 핵심 스팟으로 작동하고 있어, 개인적으로 큰 자부심을 느끼고 있습니다.\n \n시스템 디자이너로서 본인은 당시에는 짧은 시간이었지만, 단순한 총기 데이터 관리부터 시작하여 TDM & E-Sports 옵저버 및 관전 시스템 & 커스텀 룸 시스템 등 규모가 제법 시스템까지 진행한 바가 있고, 이 또한 게임의 출시까지 문제없이 잘 이끌 수 있었습니다. \n \n이후 출시를 하게되며, 저의 모든 디자인 결과들을 유저에게 직접적으로 제공할 수 있는 기회를 얻을 수 있게되었습니다. 많은 커뮤니티 피드백과 로그 및 지표분석을 토대로 저의 기획을 냉철하게 다시 바라볼 수 있었습니다. 결과가 의도한 바와 다르게 나오는 많은 부분을 직접 뼈아프게 느끼기도 하면서 개발자와 유저간의 정보와 경험의 괴리도 인지할 수 있는 좋은 경험을 느낄 수 있었다고 생각합니다. \n\n결과적으로는 NS 프로젝트 자체는 그렇게 좋은 성과로 이어지지는 못하였으나, 게임 개발의 경력 상으로 저에게 레벨과 시스템 디자이너라는 두 가지 경험을 시작하게 해주었으며 개발적 사고의 지평을 크게 넓히고 자신감을 주었습니다. 또 유저로서만 느꼈던 게임을 반대로 이를 유저에게도 전달하고 피드백 받으며 개발의 재미와 창작의 고통을 같이 느낄 수 있었던 큰 의미가 있는 프로젝트였다고 생각합니다.",
      "KIZNA":
      "C3: KIZNA는 현재 PUBG에서 진행 중인 __모바일 서브컬처 CCG(Collectible Card Game)__ 저의 3번째 프로젝트입니다. 2024년 3월부터 비공식적으로 팀 빌딩 단계부터 참여하여 현재 시스템 디자이너로서 게임의 핵심 시스템 아키텍처를 주도적으로 설계하였습니다. 초기 방향성의 정립부터 게임의 기반 설계라는 시작점 단계부터 현재까지 함께하고 현재는 자발적퇴사로 아쉽게 마무리하게 되었습니다.\n \n저는 KIZNA 팀에서 주어진 역할은 특정하게 한정되지는 않았으며, 프로젝트 재미 검증과 마일스톤 통과를 위한 어떠한 것이든 하는 것이 제 역할이자 목표였다고 할 수 있을 것 같습니다. 그러면서도 이러한 모든 과정은 라이브 출시를 항상 대비할 수 있는 상태로 준비를 해야만했습니다. \n \n팀 내에서는 핵심적으로 아래와 같은 작업들을 진행하였습니다.\n \n- 캐릭터 기본 정보, 스킬, 효과(Ability) 시스템 설계\n\n- 덱 빌딩 및 전투 시스템 설계\n\n- 몬스터 & AI 시스템 기획\n\n- 캐릭터 조합에 따른 시너지 효과 시스템\n\n- 이벤트 처리 및 게임 상태 관리 시스템\n\n- 가챠 시스템 설계 및 확률 구조 기획 등\n\n- 로컬라이징 협업 시스템 구축 \n\n- 서비스 운영툴 기획 등 \n \n그 중에서도 핵심적인 성과로 보는 요소는 '시스템을 이해만 하면 비프로그래머들이 모든 영역을 의도대로 디테일하게 만들어내고 테스트할 수 있는 환경을 초기에 만들어보자! 불편하게 계속 Tech 팀에게 찾아가 만들어달라고 할 필요 없이!'라는 취지에서 만들어낸 __데이터 중심의 개발 주도__라고 생각합니다. 아쉽지만 이를 완벽하게 끝내고 오지는 못하였습니다만, 수 십개의 캐릭터와 수 십개의 다양한 몬스터들을 빠른시간 안에 만들어내고, 스킬과 효과를 조립하여 다양한 형태로 적용할 수 있는 기반 시스템을 닦을 수 있었습니다. \n \n마지막으로 해당 프로젝트에서 개발자로서의 성장 혹은 성과가 무엇이냐고 한다면, NS와 MC프로젝트에서 거치면서 배워왔던 게임 개발의 방식을 0단계에서부터 본인이 주도적으로 참여 및 설계하고 협업해보면서 실제로 '의미 있는 개발이 되는지?' '내가 주도한 시스템으로 협업이 원활하게 이끌어지는지?', '개발 단계에서는 라이브 대응을 위해선 무엇을 고민해야하는지?'등을 확인하고 고민하고 실천할 수 있었던 시간이라 너무나 뜻 깊고 갚진 경험이었다고 생각합니다.(또 장르적으로도 서브컬쳐라는 환경에서 일하는 것도 너무나 좋았던 부분도 있습니다.)",
      "TrinitySurvivors":
      "Trinity Survivors(MC 프로젝트)는 Flyway Games에서 개발 되었던 PC 플랫폼 __슈팅 로그라이크__ 게임이고 저의 2번째 프로젝트입니다. 2022년 8월부터 약 1년간 6개월간 참여하여 시스템 디자이너로 참여하였으나 직무 범위에 구애되지 않은 업무를 진행하였습니다. 시스템 기획과 더불어 기믹 설계 및 구현, 컨텐츠 레벨 디자인 및 프로토타입, 등을 진행했습니다.\n\n이 프로젝트에서의 본인의 핵심 임무는 '개발 리더쉽이 원하는 것을 빠르게 검증하는 것'과 '게임의 기반 설계'였습니다. \n \n- 게임 내 다양한 함정, 장애물, 환경 요소들의 기믹 설계 및 프로토타이핑\n\n- 멀티모드(PVEPVP) 검증\n\n- 보스 시스템\n\n- 소환수 시스템\n\n- 게임플레이 검증을 위한 빠른 프로토타이핑 및 반복 테스트\n\n- 아이템 시스템(아티팩트) 설계 및 데이터 구조 기획 등의 작업을 진행하였으며, \n \nTrinitySurvivors 프로젝트는 제게 __게임 개발의 초기 단계부터 체계적으로 배울 수 있는 기회__를 제공했습니다. 특히 Flyway Games의 스타트업 문화 속에서 신속한 프로토타이핑의 중요성과, 초기에 핵심 재미를 검증하는 것의 가치를 깊이 있게 체득할 수 있었으며, 이렇게 복잡한 시스템 요소들을 명확한 규칙으로 정리하고, 피드백 루프를 빠르게 돌리며 게임 경험을 개선하는 과정은 이후 KIZNA 프로젝트에서의 아키텍처를 설계할 때 큰 자산이 되었습니다. \n\n이 프로젝트 경험을 통해 저는 단순히 데이터를 관리하는 디자이너에서 벗어나, 게임의 구조와 흐름을 설계하고 팀 전체의 생산성을 높일 수 있는 방안을 고민하는 개발자로 성장할 수 있었다고 생각합니다.",
  },
  projectLogos: {
    KIZNA: "/images/kizna-logo.png",
    "PUBG:NewState": "/newstate-mobile-logo.png",
    TrinitySurvivors: "/flyway-games-logo.png",
  },
  projectGenres: {
    KIZNA: ["CCG", "서브컬처"],
    "PUBG:NewState": ["배틀로얄", "FPS"],
    TrinitySurvivors: ["로그라이크", "슈팅"],
  },
  projects: [
    // ============ LEVEL DESIGN ============
    // --- PUBG:NewState ---
    {
      title: "가메시 제작 정리",
      category: "level design",
      project: "PUBG:NewState",
      image: "/portfolio/NS_LevelDesign_GrayScale_thumbnail.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/NewState_LevelDesign_GrayScale-L1n4OnpXlpaGXvjolCX8alZprK8B94.pdf",
      description: "주요 건물 가메시 작업 정리",
      tech: ["UE4", "Level Design", "Gameplay Layout"],
    },
    {
      title: "월드 디자인",
      category: "level design",
      project: "PUBG:NewState",
      image: "/portfolio/NS_LevelDesign_World.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/NS_LevelDesign_World-zX8n7973Uyfzvn2fy76GqV5NfyK6bR.pdf",
      description: "오픈 월드 맵 레벨 디자인 및 지형 구성",
      tech: ["UE4", "Level Design", "World Building"],
    },
    {
      title: "스팟 디자인",
      category: "level design",
      project: "PUBG:NewState",
      image: "/portfolio/NS_LevelDesign_Spot.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/NS_LevelDesign_Spot-v7AMROxFftST6uubKJob8oY4pLu7fV.pdf",
      description: "주요 거점(POI) 스팟 레벨 디자인",
      tech: ["UE4", "Level Design", "POI Design"],
    },
    {
      title: "건물 디자인",
      category: "level design",
      project: "PUBG:NewState",
      image: "/portfolio/NS_LevelDesign_Building.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/NS_LevelDesign_Building-WC0JS7z7IxBq8nEkaTaX8OwmQ7APkw.pdf",
      description: "건물 내외부 레벨 디자인 및 구조 설계",
      tech: ["UE4", "Level Design", "Architecture"],
    },
    {
      title: "TDM 디자인",
      category: "level design",
      project: "PUBG:NewState",
      image: "/portfolio/NS_LevelDesign_TDM.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/NS_LevelDesign_TDM-qTHWNwyXdpY9B2prnuVfPnX9k3CXLx.pdf",
      description: "팀 데스매치 전용 맵 레벨 디자인",
      tech: ["UE4", "Level Design", "Arena Design"],
    },

    // ============ PROTOTYPING ============
    // --- PUBG:NewState ---
    {
      title: "블루프린트 디자인",
      category: "prototyping",
      project: "PUBG:NewState",
      image: "/portfolio/NS_LevelDesign_BluePrint.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/NS_LevelDesign_BluePrint-LoYuPf1J4EqYeMusge2hqaUllgMTpW.pdf",
      description: "UE4 블루프린트를 활용한 게임플레이 프로토타이핑",
      tech: ["UE4", "Blueprint", "Prototyping"],
    },
    // --- MC (TrinitySurvivors) ---
    {
      title: "모드 프로토타이핑",
      category: "prototyping",
      project: "TrinitySurvivors",
      image: "/portfolio/MC_Project_Prototyping.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/MC_Project_Prototyping-8kLj55lqWJdPTMNEFD9krQX5jEtozH.pdf",
      description: "멀티 모드 / PVEVP 모드 컨셉 기획 및 프로토타이핑",
      tech: ["Unity", "Prototyping", "Game Mode"],
    },
    {
      title: "기믹 기획 및 프로토타이핑",
      category: "prototyping",
      project: "TrinitySurvivors",
      image: "/portfolio/MC_Project_Gimick.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/MC_Project_Gimick-dNpzFfSFUTv9Dw7y6MijQQrqPv0Zet.pdf",
      description: "게임 내 기믹 요소 기획 및 프로토타이핑",
      tech: ["Unity", "Prototyping", "Game Design"],
    },

    // ============ SYSTEM DESIGN ============
    // --- KIZNA ---
    {
      title: "KIZNA 데이터 아키텍처 요약",
      category: "system design",
      project: "KIZNA",
      image: "/portfolio/KIZNA_System_Architecture.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/KIZNA_System_Architecture-TYoXVaJtMK0i4ANQDuppdsTqZjGInN.pdf",
      description:
        "CCG 게임 특성상 많은 캐릭터를 빠르게 테스트하고 의도대로 구축할 수 있는 데이터 중심(Data-Driven) 아키텍처 설계",
      tech: ["Unity", "Architecture", "Data-Driven"],
    },
    {
      title: "캐릭터 시스템",
      category: "system design",
      project: "KIZNA",
      image: "/portfolio/KIZNA_System_CharacterSystem.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/KIZNA_System_CharacterSystem-vfg49FA7POg2M4as1mpcRzgtH58hOp.pdf",
      description:
        "CCG 덱빌딩 기반 캐릭터 시스템 설계. 기본정보, 외형, 능력, 스킬 등을 보유하고 유저가 수집하고 성장시킬 수 있는 LIVE 대응 시스템 개발",
      tech: ["Unity", "Data Architecture", "System Design"],
    },
    {
      title: "몬스터 시스템",
      category: "system design",
      project: "KIZNA",
      image: "/portfolio/KIZNA_System_Enemey.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/KIZNA_System_Enemey-0zv9tOU4mlb2RWRM3V4NLtjYxEQNt2.pdf",
      description: "적 유닛(몬스터) 시스템 설계 및 AI 행동 패턴 기획",
      tech: ["Unity", "AI", "System Design"],
    },
    {
      title: "몬스터 AI 시스템",
      category: "system design",
      project: "KIZNA",
      image: "/portfolio/KIZNA_System_AI.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/KIZNA_System_AI-u3Egaxsboaho66jphjYZoa0F36QC5l.pdf",
      description: "몬스터 AI 행동 트리 및 상태 머신 기반 AI 시스템 설계",
      tech: ["Unity", "AI", "Behavior Tree"],
    },
    {
      title: "이벤트 시스템",
      category: "system design",
      project: "KIZNA",
      image: "/portfolio/KIZNA_System_Event.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/KIZNA_System_Event-zi7EAs4laKZAbiLvNzW1Fjl7kR2hZp.pdf",
      description: "게임 내 이벤트 처리 시스템 설계 및 구현",
      tech: ["Unity", "Event System", "System Design"],
    },
    {
      title: "덱 시스템",
      category: "system design",
      project: "KIZNA",
      image: "/portfolio/KIZNA_System_Deck.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/KIZNA_System_Deck-UOgw8fnROAFM8UyHNcASt2ldlzVrvf.pdf",
      description:
        "보유 캐릭터를 인게임에 투입할 대상을 지정하는 덱 빌딩 시스템 기획 및 설계. 덱 프리셋, 자동 배치, 상세보기 연결 등 구현",
      tech: ["Unity", "UI/UX", "System Design"],
    },
    {
      title: "시너지 시스템",
      category: "system design",
      project: "KIZNA",
      image: "/portfolio/KIZNA_System_Synergy.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/KIZNA_System_Synergy-EmYMJx336IvPc8tb6yrX13HxQmBXLX.pdf",
      description: "캐릭터 조합에 따른 시너지 효과 시스템 설계",
      tech: ["Unity", "Balance Design", "System Design"],
    },
    {
      title: "스킬 시스템",
      category: "system design",
      project: "KIZNA",
      image: "/portfolio/KIZNA_System_Skill.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/KIZNA_System_Skill-5vmOsjYBwCedGTYeuxFFHT2RidWvwB.pdf",
      description: "캐릭터 스킬 시스템 설계 및 스킬 데이터 구조 기획",
      tech: ["Unity", "Combat System", "System Design"],
    },
    {
      title: "효과 시스템",
      category: "system design",
      project: "KIZNA",
      image: "/portfolio/KIZNA_System_Ability.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/KIZNA_System_Ability-ctYhYt57wypWuOldDBWZtTn0EIipJ8.pdf",
      description: "캐릭터 효과(Ability) 시스템 설계 및 데이터 구조 기획",
      tech: ["Unity", "Effect System", "System Design"],
    },
    {
      title: "가챠 시스템",
      category: "system design",
      project: "KIZNA",
      image: "/portfolio/KIZNA_System_Gacha.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/KIZNA_System_Gacha-7IUJykMa3SZt1brGq4g8Dx2wX5JzaK.pdf",
      description: "캐릭터 획득을 위한 가챠 시스템 설계 및 확률 구조 기획",
      tech: ["Unity", "Monetization", "System Design"],
    },
    // --- PUBG:NewState ---
    {
      title: "총기 시스템",
      category: "system design",
      project: "PUBG:NewState",
      image: "/portfolio/NS_System_GunSystem.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/NS_System_GunSystem-M1eZGcJBIQFKnahc5Rk2y2fsHEGljb.pdf",
      description: "총기 시스템 데이터 관리 및 추가 파츠 시스템(부착물 외형 및 총기 개조) 데이터 구축 참여",
      tech: ["UE4", "Data Management", "System Design"],
    },
    {
      title: "총기 프리셋 시스템",
      category: "system design",
      project: "PUBG:NewState",
      image: "/portfolio/NS_System_GunPreset.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/NS_System_GunPreset-S1yYSBDWeQwzDcMDVJ6oy96Z4khebQ.pdf",
      description: "총기 선택 및 부착물 선택 기능, 총기별 달성 기록 로그 표기 시스템 기획 및 개발",
      tech: ["UE4", "System Design", "UI/UX"],
    },
    {
      title: "TDM 시스템",
      category: "system design",
      project: "PUBG:NewState",
      image: "/portfolio/NS_System_TDM.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/NS_System_TDM-z3IYEnymHmlk0amURzdqZw927wsprj.pdf",
      description: "팀 데스매치 모드 시스템 기획, 인게임 룰(Rule) 및 TDM 전용 UX 개발 주도",
      tech: ["UE4", "Game Mode", "System Design"],
    },
    {
      title: "미니맵 피드백 시스템",
      category: "system design",
      project: "PUBG:NewState",
      image: "/portfolio/NS_System_MiniMap.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/NS_System_MiniMap-IZABxVqfYSAOe7sd1VJDyFt4rRJol1.pdf",
      description:
        "총기 사운드, 적 발자국(인기척), 차량, 폭탄 등 다양한 이벤트를 미니맵에 반영하는 시스템 기획 및 개발",
      tech: ["UE4", "System Design", "Audio"],
    },
    {
      title: "옵저버 & 관전 시스템",
      category: "system design",
      project: "PUBG:NewState",
      image: "/portfolio/NS_System_Observer.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/NS_System_Observer-7BGs33ZH1Shva5SnkEDF8tJJSJYb6n.pdf",
      description:
        "대회 및 옵저버 환경을 위한 캐릭터 특수 처리(X-Ray, DepthOutLine), 월드맵 유저 트래킹, 옵저빙 카메라 동작 시스템 기획 및 개발",
      tech: ["UE4", "Esports", "Camera System"],
    },
    {
      title: "커스텀 룸 시스템",
      category: "system design",
      project: "PUBG:NewState",
      image: "/portfolio/NS_System_CustomRoom.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/NS_System_CustomRoom-1vVdJGIaIf62fuLC0o2wnIi7ONRaxT.pdf",
      description:
        "유저들이 방을 생성하고 같이 플레이할 수 있는 룸 시스템 개발, 호스트 기능, 고급 설정(아이템 스폰), 대회용 방 구분 기능",
      tech: ["UE4", "Multiplayer", "UI/UX"],
    },
    // --- MC (TrinitySurvivors) ---
    {
      title: "아티팩트 시스템",
      category: "system design",
      project: "TrinitySurvivors",
      image: "/portfolio/MC_Project_Artifact.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/MC_Project_Artifact-00ejWdQ3gBATtvKBfCpL0IhQzGT2n6.pdf",
      description: "아티팩트 아이템 시스템 설계 및 데이터 구조 기획",
      tech: ["Unity", "Item System", "System Design"],
    },
    {
      title: "소환수 시스템",
      category: "system design",
      project: "TrinitySurvivors",
      image: "/portfolio/MC_Project_Summon.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/MC_Project_Summon-hwOjSD0mWCYbrPdluIcTb2zXWOMc8n.pdf",
      description: "소환수 시스템 설계 및 AI 행동 패턴 기획",
      tech: ["Unity", "AI", "System Design"],
    },
    {
      title: "보스 시스템",
      category: "system design",
      project: "TrinitySurvivors",
      image: "/portfolio/MC_Project_Boss.jpg",
      pdfUrl: "https://blobs.vusercontent.net/blob/MC_Project_Boss-CKsvD8jqeop20pXTcUuW5LTDT9ecgZ.pdf",
      description: "보스 몬스터 시스템 설계 및 패턴 기획",
      tech: ["Unity", "AI", "Boss Design"],
    },
  ],
}

export const contactData = {
  email: "dbsghdyd3000@gmail.com",
  phone: "+82 (10) 4438-4384",
  location: "Gangnam-gu, Seoul, Republic of Korea",
  mapEmbedUrl:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3165.2857917718796!2d127.0059517!3d37.4907231!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzfCsDI5JzI2LjYiTiAxMjfCsDAwJzIxLjQiRQ!5e0!3m2!1sen!2skr!4v1234567890123!5m2!1sen!2skr",
}

export const gamesData = {
  currentGames: [
    {
      id: 1,
      name: "아이온 2",
      image: "/images/aion-2.png",
      playTime: "200+h",
      notes: "Asia Server / MMORPG / 천족 만렙 4개(수호성(3000+), 마도성(2300+), 궁성(2100+), 살성(1900+))",
      genre: "MMORPG",
    },
    {
      id: 2,
      name: "원신",
      image: "/genshin-impact-game-thumbnail.jpg",
      playTime: "500+h",
      notes: "Asia Server / UID 826334724 / 풀돌 8개 / 나타까지 완료 후 다시 복귀 / 9백만+ 과금 추정",
      genre: "액션 RPG",
    },
    {
      id: 3,
      name: "붕괴: 스타레일",
      image: "/honkai-star-rail-game-thumbnail.jpg",
      playTime: "500+h",
      notes: "Asia Server / UID 806540643 / 풀돌 30개 이상 / 이상중재 플래티넘 / 3천만+ 과금 추정",
      genre: "턴제 RPG",
    },
    {
      id: 4,
      name: "젠레스 존 제로",
      image: "/images/zenless-zone-zero.png",
      playTime: "200+h",
      notes: "효율 돌파 위주 / 6개 파티 독자 파티 보유",
      genre: "액션 RPG",
    },
    {
      id: 5,
      name: "스텔라 소라",
      image: "/stellar-sora-game-thumbnail.jpg",
      playTime: "50+h",
      notes: "소소하게 진행중인 게임 / 요스타 트렌드 참고용",
      genre: "RPG",
    },
    {
      id: 6,
      name: "리그 오브 레전드",
      image: "/images/league-of-legends.png",
      playTime: "500+h",
      notes: "정글 / 골드 ㅎ",
      genre: "MOBA",
    },
  ],
  pastGames: [
    {
      id: 1,
      name: "33 원정대",
      image: "/expedition-33.jpg",
      playTime: "Completed",
      notes: "최고의 게임. 디자인 아트 사운드 모두 만족스러웠던 근래 최고의 게임",
      genre: "TRPG(CRPG)",
    },
    {
      id: 2,
      name: "엘든 링",
      image: "/elden-ring.jpg",
      playTime: "Completed",
      notes: "소울라이크 대작. 어려움과 대중성이 공존할 수 있는 모범이 되는 게임",
      genre: "액션 RPG",
    },
    {
      id: 3,
      name: "젤다의 전설: 브레스 오브 더 와일드",
      image: "/zelda-botw.jpg",
      playTime: "Completed",
      notes: "오픈월드 명작. 게임이 디자인적으로 참 우아하고 아름다운 느낌",
      genre: "액션 어드벤처",
    },
    {
      id: 4,
      name: "명조",
      image: "/images/wuthering-waves-new.png",
      playTime: "100+h",
      notes: "모바일 액션 RPG",
      genre: "모바일 RPG",
    },
    {
      id: 5,
      name: "사이버펑크 2077",
      image: "/images/cyberpunk2077.jpg",
      playTime: "100+ h",
      notes: "오픈월드 RPG / 나이트 시티를 배경으로 한 몰입감 넘치는 스토리",
      genre: "액션 어드벤처",
    },
    {
      id: 6,
      name: "아크 레이더스",
      image: "/images/arc-raiders.png",
      playTime: "-",
      notes: "협동 루터 슈터, 익스트렉션 장르의 대중성이란 이런 것을 느꼈던 게임",
      genre: "루터 슈터",
    },
    {
      id: 7,
      name: "PUBG: BATTLEGROUNDS",
      image: "/images/pubg-battlegrounds.png",
      playTime: "1000+h",
      notes: "배틀로얄 장르의 선구자 / KRAFTON 재직 시 주요 프로젝트",
      genre: "FPS",
    },
    {
      id: 8,
      name: "발로란트",
      image: "/images/valorant.png",
      playTime: "-",
      notes: "전술 FPS",
      genre: "FPS",
    },
    {
      id: 9,
      name: "오버워치",
      image: "/images/overwatch.png",
      playTime: "-",
      notes: "팀 기반 FPS",
      genre: "FPS",
    },
    {
      id: 10,
      name: "콜 오브 듀티: 워존",
      image: "/images/cod-warzone.png",
      playTime: "-",
      notes: "배틀로얄 FPS",
      genre: "FPS",
    },
    {
      id: 11,
      name: "콜 오브 듀티: 블랙 옵스 시리즈",
      image: "/images/codblackops.jpg",
      playTime: "-",
      notes: "FPS 시리즈",
      genre: "FPS",
    },
    {
      id: 12,
      name: "더 디비전 2",
      image: "/images/division-2.jpg",
      playTime: "-",
      notes: "TPS 루터 슈터",
      genre: "루터 슈터",
    },
    {
      id: 13,
      name: "스페셜 포스",
      image: "/images/special-force.png",
      playTime: "3000+h",
      notes: "FPS / 중학생 시절 저는 또래와 모든 어른들을 농락했습니다.",
      genre: "FPS",
    },
    {
      id: 14,
      name: "월드 오브 워크래프트",
      image: "/world-of-warcraft.jpg",
      playTime: "-",
      notes: "MMORPG / 리분유저 죽기(냉죽/혈탱) 플레이",
      genre: "MMORPG",
    },
    {
      id: 15,
      name: "블레이드 앤 소울",
      image: "/blade-and-soul.jpg",
      playTime: "-",
      notes: "MMORPG / 주술사 - 당시 '파천성도' 최고 레이드 클리어",
      genre: "MMORPG",
    },
    {
      id: 16,
      name: "바람의나라:연",
      image: "/images/baram-yeon-new.png",
      playTime: "1000+h",
      notes: "전서버 1위 문파의 최상위 랭커 중 한명 출신 '야수' / 수천만원 과금",
      genre: "모바일 RPG",
    },
    {
      id: 17,
      name: "블루 아카이브",
      image: "/images/blue-archive.png",
      playTime: "200+h",
      notes: "모바일 RPG / 대결전 인세인(Insane) 100% 플레 가능 파티로 구성",
      genre: "모바일 RPG",
    },
    {
      id: 18,
      name: "버섯커 키우기",
      image: "/images/mushroom-grower.png",
      playTime: "-",
      notes: "방치형 RPG / 클러스터 서버 랭킹 ~3위 / 과금 3백만원 이상",
      genre: "방치형 RPG",
    },
    {
      id: 19,
      name: "트릭스터 M",
      image: "/images/trickster-m.png",
      playTime: "-",
      notes: "모바일 MMORPG / 서버 1~2위 라인 길드 / 과금 2천만원 이상",
      genre: "MMORPG",
    },
    {
      id: 20,
      name: "승리의 여신: 니케",
      image: "/images/nikke.png",
      playTime: "-",
      notes: "모바일 슈팅 RPG",
      genre: "모바일 RPG",
    },
    {
      id: 21,
      name: "마비노기 모바일",
      image: "/images/mabinogi-mobile-new.png",
      playTime: "-",
      notes: "모바일 MMORPG",
      genre: "MMORPG",
    },
    {
      id: 22,
      name: "소녀전선 2: 망명",
      image: "/images/girls-frontline-2.png",
      playTime: "-",
      notes: "모바일 전략 RPG",
      genre: "TRPG(CRPG)",
    },
    {
      id: 23,
      name: "신월동행",
      image: "/images/shinwol-donghaeng.png",
      playTime: "-",
      notes: "서브컬처 참고용 게임",
      genre: "TRPG(CRPG)",
    },
    {
      id: 24,
      name: "하데스",
      image: "/images/hades-1.png",
      playTime: "Completed",
      notes: "로그라이크 명작",
      genre: "로그라이크",
    },
    {
      id: 25,
      name: "하데스 2",
      image: "/images/hades-2.png",
      playTime: "Completed",
      notes: "로그라이크 명작",
      genre: "로그라이크",
    },
    {
      id: 26,
      name: "슬레이 더 스파이어",
      image: "/images/slay-the-spire.png",
      playTime: "Completed",
      notes: "덱빌딩 로그라이크",
      genre: "로그라이크",
    },
    {
      id: 27,
      name: "다키스트 던전",
      image: "/images/darkest-dungeon-1.png",
      playTime: "Completed",
      notes: "턴제 로그라이크",
      genre: "로그라이크",
    },
    {
      id: 28,
      name: "다키스트 던전 2",
      image: "/images/darkest-dungeon-2.png",
      playTime: "Completed",
      notes: "턴제 로그라이크",
      genre: "로그라이크",
    },
    {
      id: 29,
      name: "발라트로",
      image: "/images/balatro.png",
      playTime: "50+ h",
      notes: "덱빌딩 로그라이크",
      genre: "로그라이크",
    },
    {
      id: 30,
      name: "몬스터 트레인 2",
      image: "/images/monster-train-2.png",
      playTime: "50+ h",
      notes: "덱빌딩 로그라이크",
      genre: "로그라이크|타워 디펜스",
    },
    {
      id: 31,
      name: "패스 오브 엑자일 2",
      image: "/path-of-exile-2.jpg",
      playTime: "100+ h",
      notes: "핵앤슬래시 RPG / Lv 98",
      genre: "핵앤슬래시",
    },
    {
      id: 32,
      name: "라스트 에폭",
      image: "/last-epoch.jpg",
      playTime: "150+ h",
      notes: "핵앤슬래시 RPG / 오염도 900+ 돌파",
      genre: "핵앤슬래시",
    },
    {
      id: 33,
      name: "디아블로 3",
      image: "/diablo-3.jpg",
      playTime: "-",
      notes: "핵앤슬래시",
      genre: "핵앤슬래시",
    },
    {
      id: 34,
      name: "디아블로 4",
      image: "/diablo-4.jpg",
      playTime: "-",
      notes: "핵앤슬래시",
      genre: "핵앤슬래시",
    },
    {
      id: 35,
      name: "크리티카 RPG",
      image: "/images/kritika-rpg.png",
      playTime: "-",
      notes: "핵앤슬래시 액션 RPG",
      genre: "액션 RPG",
    },
    {
      id: 36,
      name: "토치라이트 2",
      image: "/torchlight-2.jpg",
      playTime: "Completed",
      notes: "핵앤슬래시 RPG",
      genre: "핵앤슬래시",
    },
    {
      id: 37,
      name: "트라인 4",
      image: "/trine-4.jpg",
      playTime: "Completed",
      notes: "협동 퍼즐 플랫포머 / 인생 퍼즐게임",
      genre: "퍼즐",
    },
    {
      id: 38,
      name: "트라인 5",
      image: "/trine-5.jpg",
      playTime: "Completed",
      notes: "협동 퍼즐 플랫포머 / 인생 퍼즐게임",
      genre: "퍼즐",
    },
    {
      id: 39,
      name: "브이 라이징",
      image: "/vrising.jpg",
      playTime: "Completed",
      notes: "뱀파이어 생존",
      genre: "생존",
    },
    {
      id: 40,
      name: "뱀파이어 서바이버즈",
      image: "/vampire-survivors.jpg",
      playTime: "Completed",
      notes: "로그라이크 슈터",
      genre: "로그라이크",
    },
    {
      id: 41,
      name: "위 워 히어 시리즈",
      image: "/we-were-here.jpg",
      playTime: "Completed",
      notes: "협동 퍼즐 게임",
      genre: "퍼즐",
    },
    {
      id: 42,
      name: "파티 애니멀즈",
      image: "/images/party-animals.png",
      playTime: "-",
      notes: "캐주얼 멀티플레이어 파티 게임",
      genre: "파티",
    },
    {
      id: 43,
      name: "폴 가이즈",
      image: "/fall-guys.jpg",
      playTime: "-",
      notes: "파티 게임",
      genre: "파티",
    },
    {
      id: 44,
      name: "스타크래프트 1~2",
      image: "/starcraft-2.jpg",
      playTime: "500+ h",
      notes: "RTS 명작 / 스타 2 자유의 날개 마스터",
      genre: "전략",
    },
    {
      id: 45,
      name: "디제이맥스 온라인",
      image: "/djmax-online.jpg",
      playTime: "-",
      notes: "리듬 게임 / 전곡 노 미쓰 클리어",
      genre: "리듬",
    },
    {
      id: 46,
      name: "몬스터 헌터 월드",
      image: "/monster-hunter-world.jpg",
      playTime: "-",
      notes: "액션 RPG / 태도&활&라보 유저",
      genre: "액션 RPG",
    },
    {
      id: 47,
      name: "발더스 게이트 3",
      image: "/baldurs-gate.jpg",
      playTime: "100+ h",
      notes: "CRPG 명작 / 주인공 촉수로 변하고 플레이 포기",
      genre: "TRPG(CRPG)",
    },
    {
      id: 48,
      name: "바람의나라",
      image: "/baram.jpg",
      playTime: "저의 인생",
      notes: "MMORPG",
      genre: "MMORPG",
    },
    {
      id: 49,
      name: "라그나로크 온라인",
      image: "/images/ragnarok-1.png",
      playTime: "-",
      notes: "MMORPG",
      genre: "MMORPG",
    },
    {
      id: 50,
      name: "라그나로크 온라인 2",
      image: "/images/ragnarok-2.png",
      playTime: "-",
      notes: "MMORPG",
      genre: "MMORPG",
    },
    {
      id: 51,
      name: "테일즈위버",
      image: "/tales-weaver.jpg",
      playTime: "-",
      notes: "MMORPG",
      genre: "MMORPG",
    },
    {
      id: 52,
      name: "메이플스토리",
      image: "/images/maplestory.png",
      playTime: "-",
      notes:
        "MMORPG / 루시드 처음 공개되던 시절, 레드서버의 팔라딘과 아란을 했으며, 팔라딘 1위를 유지하다가 접고 아란 1~2위를 유지했었음, 해당 서버 루시드 퍼클 팀이기도 했음",
      genre: "MMORPG",
    },
    {
      id: 53,
      name: "던전앤파이터",
      image: "/images/dungeon-fighter.png",
      playTime: "-",
      notes: "액션 MMORPG",
      genre: "액션 RPG",
    },
    {
      id: 54,
      name: "거상",
      image: "/images/geosang.png",
      playTime: "-",
      notes: "한국 MMORPG",
      genre: "MMORPG",
    },
    {
      id: 55,
      name: "포켓몬스터 1~7세대 (썬문)",
      image: "/images/pokemon-sun-moon.png",
      playTime: "Completed",
      notes: "RPG 시리즈",
      genre: "RPG",
    },
    {
      id: 56,
      name: "건파이어 리본",
      image: "/images/gunfire-reborn.png",
      playTime: "Completed",
      notes: "로그라이크 FPS",
      genre: "로그라이크",
    },
    {
      id: 57,
      name: "컬트 오브 더 램",
      image: "/images/cult-of-the-lamb.png",
      playTime: "Completed",
      notes: "로그라이크 경영 시뮬레이션",
      genre: "로그라이크",
    },
    {
      id: 58,
      name: "포 더 킹",
      image: "/images/for-the-king.png",
      playTime: "Completed",
      notes: "턴제 전략 RPG",
      genre: "TRPG(CRPG)",
    },
    {
      id: 59,
      name: "오크 머스트 다이! 시리즈",
      image: "/images/orcs-must-die.png",
      playTime: "Completed",
      notes: "타워 디펜스 액션",
      genre: "타워 디펜스",
    },
    {
      id: 60,
      name: "몬스터 헌터 와일즈",
      image: "/monster-hunter-wilds.jpg",
      playTime: "-",
      notes: "액션 RPG / 태도&활&라보 유저",
      genre: "액션 RPG",
    },
    {
      id: 61,
      name: "몬스터 헌터 라이즈",
      image: "/monster-hunter-rise.jpg",
      playTime: "-",
      notes: "액션 RPG / 태도&활&라보 유저",
      genre: "액션 RPG",
    },
    {
      id: 62,
      name: "발헤임",
      image: "/images/valheim.jpg",
      playTime: "150+ h",
      notes: "바이킹 생존 게임 / 협동 플레이와 건축의 재미",
      genre: "생존",
    },
  ],
}
